# Generated by Django 3.0.5 on 2021-05-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('gender', models.IntegerField(choices=[('male', 'male'), ('female', 'female')], default='male')),
            ],
        ),
    ]
