# Generated by Django 3.0.5 on 2021-05-29 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 14, 53, 3, 376708)),
        ),
    ]
