# Generated by Django 3.1.2 on 2021-06-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomanager', '0003_auto_20210602_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
